# Generated by Django 5.0.1 on 2024-01-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ensachage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ensachage',
            name='casse',
            field=models.IntegerField(null=True),
        ),
    ]
