# Generated by Django 5.0.1 on 2024-01-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ensachage', '0002_alter_ensachage_casse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ensachage',
            name='casse',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ensachage',
            name='vrac',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
