# Generated by Django 5.0.1 on 2024-01-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ensachage', '0003_alter_ensachage_casse_alter_ensachage_vrac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ensachage',
            name='ensache',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ensachage',
            name='tx_casse',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
