# Generated by Django 5.0.1 on 2024-01-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ensachage', '0004_alter_ensachage_ensache_alter_ensachage_tx_casse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ensachage',
            name='casse',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ensachage',
            name='livraison',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
