# Generated by Django 5.0.1 on 2024-01-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ensachage', '0005_alter_ensachage_casse_alter_ensachage_livraison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ensachage',
            name='casse',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ensachage',
            name='ensache',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ensachage',
            name='livraison',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ensachage',
            name='tx_casse',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
