# Generated by Django 5.0.1 on 2024-01-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ensachage', '0006_alter_ensachage_casse_alter_ensachage_ensache_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ensachage',
            name='vrac',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
