# Generated by Django 5.0.1 on 2024-02-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ensachage', '0015_rename_name_user_ensachage_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ensachage',
            name='casse',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ensachage',
            name='livraison',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
