# Generated by Django 5.0.6 on 2024-06-27 10:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ensachage', '0016_alter_ensachage_casse_alter_ensachage_livraison'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ensachage',
            new_name='EnsachageModel',
        ),
    ]
