# Generated by Django 5.0.6 on 2024-06-27 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ensachage', '0017_rename_ensachage_ensachagemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ensachagemodel',
            old_name='username',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='ensachagemodel',
            old_name='vrac',
            new_name='vrack',
        ),
    ]
