# Generated by Django 5.0.6 on 2024-06-27 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ensachage', '0018_rename_username_ensachagemodel_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ensachagemodel',
            options={'managed': True, 'verbose_name': 'Ensachage', 'verbose_name_plural': 'Ensachage'},
        ),
        migrations.AlterModelTable(
            name='ensachagemodel',
            table='',
        ),
    ]
